// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FMD0l6HCZHPQBHkJL2SwlwQRRAeGfm8',
    appId: '1:32673726083:web:adc02a4ea69f66266725b6',
    messagingSenderId: '32673726083',
    projectId: 'safeher-284e2',
    authDomain: 'safeher-284e2.firebaseapp.com',
    storageBucket: 'safeher-284e2.firebasestorage.app',
    measurementId: 'G-NLVYWSGC8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNdQgZrDGGwM49kttZ02NNeaKrYRbjO3w',
    appId: '1:32673726083:android:808b433fc331a2676725b6',
    messagingSenderId: '32673726083',
    projectId: 'safeher-284e2',
    storageBucket: 'safeher-284e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHXLmg4X_51_-wAR6jO9RY1qi9JtsN6Jc',
    appId: '1:32673726083:ios:827e75bda2d166fa6725b6',
    messagingSenderId: '32673726083',
    projectId: 'safeher-284e2',
    storageBucket: 'safeher-284e2.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHXLmg4X_51_-wAR6jO9RY1qi9JtsN6Jc',
    appId: '1:32673726083:ios:827e75bda2d166fa6725b6',
    messagingSenderId: '32673726083',
    projectId: 'safeher-284e2',
    storageBucket: 'safeher-284e2.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-FMD0l6HCZHPQBHkJL2SwlwQRRAeGfm8',
    appId: '1:32673726083:web:8501fd53f28c346c6725b6',
    messagingSenderId: '32673726083',
    projectId: 'safeher-284e2',
    authDomain: 'safeher-284e2.firebaseapp.com',
    storageBucket: 'safeher-284e2.firebasestorage.app',
    measurementId: 'G-2F5MG6D33J',
  );
}
