// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4aB1Uyrmb95rawHWLMVQ0O4T6AfSLR4',
    appId: '1:282254258843:web:617a6df47c7d5944cdcc3e',
    messagingSenderId: '282254258843',
    projectId: 'safeher-ef28d',
    authDomain: 'safeher-ef28d.firebaseapp.com',
    storageBucket: 'safeher-ef28d.firebasestorage.app',
    measurementId: 'G-PYFF4GLQ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGLR5ljGtU9Ej25Ol1hkktZODJs1S398',
    appId: '1:282254258843:android:69e9ae7551041672cdcc3e',
    messagingSenderId: '282254258843',
    projectId: 'safeher-ef28d',
    storageBucket: 'safeher-ef28d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkn4qeNUrzvFln-4-NFHenAotrj0rZryg',
    appId: '1:282254258843:ios:0a576c045732fa1ecdcc3e',
    messagingSenderId: '282254258843',
    projectId: 'safeher-ef28d',
    storageBucket: 'safeher-ef28d.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkn4qeNUrzvFln-4-NFHenAotrj0rZryg',
    appId: '1:282254258843:ios:0a576c045732fa1ecdcc3e',
    messagingSenderId: '282254258843',
    projectId: 'safeher-ef28d',
    storageBucket: 'safeher-ef28d.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW4aB1Uyrmb95rawHWLMVQ0O4T6AfSLR4',
    appId: '1:282254258843:web:dbe0a51f528cbb4ccdcc3e',
    messagingSenderId: '282254258843',
    projectId: 'safeher-ef28d',
    authDomain: 'safeher-ef28d.firebaseapp.com',
    storageBucket: 'safeher-ef28d.firebasestorage.app',
    measurementId: 'G-EDJE738ECH',
  );
}
